In [2]:
import pandas as pd
import requests

In [3]:
response=requests.get("https://jsonplaceholder.typicode.com/photos")

In [4]:
df=pd.DataFrame([response.json()[2]])

In [5]:
data=pd.DataFrame(response.json())

In [6]:
data

,albumId,id,title,url,thumbnailUrl
0,1,1,accusamus beatae ad facilis cum similique qui ...,https://via.placeholder.com/600/92c952,https://via.placeholder.com/150/92c952
1,1,2,reprehenderit est deserunt velit ipsam,https://via.placeholder.com/600/771796,https://via.placeholder.com/150/771796
2,1,3,officia porro iure quia iusto qui ipsa ut modi,https://via.placeholder.com/600/24f355,https://via.placeholder.com/150/24f355
3,1,4,culpa odio esse rerum omnis laboriosam volupta...,https://via.placeholder.com/600/d32776,https://via.placeholder.com/150/d32776
4,1,5,natus nisi omnis corporis facere molestiae rer...,https://via.placeholder.com/600/f66b97,https://via.placeholder.com/150/f66b97
...,...,...,...,...,...
4995,100,4996,voluptatem ab aliquam dolorum vel voluptas qui...,https://via.placeholder.com/600/b3db9a,https://via.placeholder.com/150/b3db9a
4996,100,4997,sunt amet autem exercitationem fuga consequatur,https://via.placeholder.com/600/13454b,https://via.placeholder.com/150/13454b
4997,100,4998,qui quo cumque distinctio aut voluptas,https://via.placeholder.com/600/315aa6,https://via.placeholder.com/150/315aa6
4998,100,4999,in voluptate sit officia non nesciunt quis,https://via.placeholder.com/600/1b9d08,https://via.placeholder.com/150/1b9d08
4999,100,5000,error quasi sunt cupiditate voluptate ea odit ...,https://via.placeholder.com/600/6dd9cb,https://via.placeholder.com/150/6dd9cb